{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chema-vnext.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
